token: ODczODk1MDg1MjA3NTk3MDk3.GE3ErD.l75BGOreAMkqA6nuN2O3Is9DmKm-iVnYsj7XWE
logs: debug
lavalink_host: lavalink
lavalink_password: youshallnotpass
audioservice: false

ConnectionStrings:
  Default: Host=localhost;Database=grechkadb;Username=postgres;Password=0270;

version: 5.0