token: NzMwNzQ1NzAxNzU0OTk0Njk0.GxAuPV.v4mzQnODXiczwNYPp7fSyvsWZrT7DfVkSjLb7A
logs: debug
pg_user: docker
password: admin
db: grechkadb
port_db: 5432
host_db: db
lavalink_host: lavalink
lavalink_password: youshallnotpass

